### ISSUE TITLE
No getLine in ClassyPrelude

### ISSUE THREAD

**Issue by beojan** [snoyberg/mono-traversable#146]
It appears there's no `getLine` in ClassyPrelude. Is this intentional or an oversight?

**Comment by snoyberg** [comment]
Mostly on oversight, though the correct type to use is slightly sensitive.
I'm assuming you're thinking of `getLine :: MonadIO m => m Text`, am I
correct?

On Sat, Dec 2, 2017 at 12:39 PM, Beojan Stanislaus <notifications@github.com

**Comment by beojan** [comment]
Yes. In fact all the prelude terminal input  actions seem to be missing.

**Comment by snoyberg** [comment]
I'm pretty sure I avoided it because there's some serious ugliness around these things due to dependence on environment variables. See https://www.snoyman.com/blog/2016/12/beware-of-readfile. But the terminal-oriented functions should be fine, as long as the caveats are documented. You interested in sending a PR?

**Comment by beojan** [comment]
Submitted (https://github.com/snoyberg/mono-traversable/pull/148).

**Comment by snoyberg** [comment]
Fixed by #148, thanks!
