### ISSUE TITLE
Filtering with key

### ISSUE THREAD

**Issue by L0neGamer** [snoyberg/mono-traversable#218]
there are methods in the Containers module for filtering values within a container, but unlike many other functions there is not a method to filter with the container key. Would it be possible to add that to the typeclasses?

**Comment by BebeSparkelSparkel** [comment]
Could you create an example interface that demonstrates exactly what you are looking for?

It seems like this could also used with indexed collections.

**Comment by L0neGamer** [comment]
Just as we have 

```hs
    updateMap
        :: (MapValue map -> Maybe (MapValue map))
        -> ContainerKey map -- ^ key
        -> map              -- ^ input map
        -> map              -- ^ resulting map

    updateWithKey
        :: (ContainerKey map -> MapValue map -> Maybe (MapValue map))
        -> ContainerKey map -- ^ key
        -> map              -- ^ input map
        -> map              -- ^ resulting map
```

we should have `filterMap` have a sibling function `filterWithKey`:

```hs

    filterMap :: IsMap map => (MapValue map -> Bool) -> map -> map

    filterWithKey :: IsMap map => (ContainerKey map -> MapValue map -> Bool) -> map -> map
```

One further thing I've noticed is that there seems to be an unneccessary `IsMap` constraint on filterMap, which it would be worth removing if possible just for cleanliness.

**Comment by BebeSparkelSparkel** [comment]
Seems like a fine idea.

Currently, `filterMap` default implementation is `filterMap p = mapFromList . filter (p . snd) . mapToList` but could be changed to use `filterWithKey` instead of `mapFromList`. Then the default implementation of `filterWithKey` could use `mapToList` like current `filterMap`. I don't think that would change the performance of existing instances that use it. What do you think of this? 

If you find this satisfactory, could you create a PR? Also, the unnecessary constraint can be cleaned in this change.

**Comment by BebeSparkelSparkel** [comment]
@gregwebs Do you see any problems removing the `IsMap` constraint from `filterMap`?

**Comment by gregwebs** [comment]
FilterWithKey makes sense to me. I don't know why the extra constraint was placed there.

**Comment by gregwebs** [comment]
so yeah it makes sense to remove it

**Comment by L0neGamer** [comment]
The suggested default implementation sounds fine to me, and I would be happy to make a PR in due course; I'm a bit busy currently however, so if someone wants to take a crack by all means go for it.
