### ISSUE TITLE
Add polymorphic container functions

### ISSUE THREAD

**Issue by GallagherCommaJack** [snoyberg/mono-traversable#93]
Is there any good reason to keep the list specialization of functions like `___FromList` and `__ToList`?

If we actually want people to be able to use vectors and sequences instead of lists everywhere, it seems like we shouldn't make them convert back and forth when they want to construct or destruct containers.

**Comment by snoyberg** [comment]
I see two reasons:

1. Performance. The underlying Map/IntMap/HashMap/etc functions all work in
terms of lists. Converting to a Vector or something else adds a performance
overhead that may not be obvious from the polymorphic type signature.
2. Type inference. Since it's common to convert to a list and then do
something like a fold, returning a polymorphic value may be too much type
freedom and annoyingly require type signatures.

**Comment by GallagherCommaJack** [comment]
2. makes sense - looking through the code that made me post this issue, I realize I didn't actually need anything but list output.

As for 1, there are two ideas that jump out at me:
a) This seems like the sort of double-fold that a compiler ought to be able to optimize away. I don't have the right expertise yet to figure out if GHC is indeed accomplishing this, but I put decent odds on it being possible with some well-crafted rewrite rules.
b) It's probably worth looking at the underlying implementations to see how plausible it is to port them to classier types (if they're just folds there's no reason for lists to have all the fun). That said, this sets off alarms for potentially unnecessary duplication of functionality.
